# Firegate NFTables Configuration

#!/usr/sbin/nft -f

table inet firegate_filter {
	chain input {
		type filter hook input priority filter; policy drop;
	
		iifname "lo" accept
	
		ct state established,related accept
	
		# Debugging Purpouses
		ip protocol icmp accept
	
	}

	chain forward {
		type filter hook forward priority filter; policy drop;
		
		iifname "eth1" oifname "eth0" accept
		
		iifname "eth0" oifname "eth1" ct state established,related accept
	}

	chain output {
		type filter hook output priority filter; policy accept;
	}

}

table ip firegate_nat {
	chain postrouting {
		type nat hook postrouting priority srcnat; policy accept;
		
		oifname "eth0" masquerade
	}
}
